### ISSUE TITLE
Formatting messed up on first two blog posts

### ISSUE THREAD

**Issue by fvbommel** [yoadsn/yoadsn.github.io#2]
The formatting on [Configure HTTPS with HTTP.sys for self hosted web servers](http://blog.boxofbolts.com/ssl/windows/owin/guide/2015/06/29/https-self-hosted-windows/) and [Plato's Cave - Attending IDesign Master Classes](http://blog.boxofbolts.com/thoughts/software/architecture/2015/07/25/attending_idesigns_master_classes/) seems to be messed up.

Raw `#` characters are showing up.

**Comment by yoadsn** [comment]
Thanks - probably the static site generator is screwed up - I should replace this anyway at some point.

**Comment by yoadsn** [comment]
Thank you so much @fvbommel - I truly appreciate your help on this!
